# Generated by Django 4.1.3 on 2022-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.IntegerField(verbose_name='Cd_Paciente')),
                ('dt_attendance', models.DateField(verbose_name='Data_Atendimento')),
                ('cd_convenio', models.IntegerField(verbose_name='CD_CONVENIO')),
            ],
        ),
        migrations.CreateModel(
            name='Health_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome_Convenio')),
                ('cd_convenio', models.IntegerField(verbose_name='CD_CONVENIO')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome :')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('gender', models.CharField(max_length=1, verbose_name='Sexo')),
            ],
        ),
    ]
