# Generated by Django 4.1.3 on 2022-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_convenio', models.IntegerField(verbose_name='cd_convenio')),
                ('nm_convenio', models.CharField(max_length=60, verbose_name='nm_convenio')),
                ('sn_fatura_ambulatorio_sus', models.CharField(max_length=1, verbose_name='SN_FATURA_AMBULATORIO_SUS')),
                ('sn_cobra_insumos', models.CharField(max_length=1, verbose_name='SN_COBRA_INSUMOS')),
                ('tp_convenio', models.CharField(max_length=1, verbose_name='TP_CONVENIO')),
                ('cd_for_apre', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='CD_FOR_APRE')),
                ('tp_forma_agrupamento', models.CharField(max_length=1, verbose_name='TP_FORMA_AGRUPAMENTO')),
                ('tp_importar_matmed', models.CharField(max_length=1, verbose_name='TP_IMPORTAR_MATMED')),
                ('ds_bairro', models.CharField(max_length=100, verbose_name='BAIRRO')),
                ('ds_cidade', models.CharField(max_length=100, verbose_name='CIDADE')),
                ('ds_endereco', models.CharField(max_length=100, verbose_name='ENDERECO')),
                ('ds_uf', models.CharField(max_length=2, verbose_name='UF')),
                ('nr_cgc', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('nr_fone', models.CharField(max_length=11, verbose_name='FONE')),
                ('nr_cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('nm_razao_social', models.CharField(max_length=60, verbose_name='RAZÃO SOCIAL')),
                ('sn_ativo', models.CharField(max_length=1, verbose_name='ATIVO')),
                ('nr_endereco', models.CharField(max_length=10, verbose_name='Nº:')),
                ('ds_complemento', models.CharField(max_length=60, verbose_name='Complemento')),
            ],
        ),
    ]
